### ISSUE TITLE
No installation of Tosca could be found. Make sure it is correctly installed before running this script.

### ISSUE THREAD

**Issue by ErVigue** [Neotys-Labs/Tricentis-Tosca#12]
Hi experts, 

When I run the bat file I've got an error saying I do not have a Tosca. When I try to run the bat file in "C:\Program Files (x86)\TRICENTIS\Tosca Testsuite" I;ve got a new error message "C:/Program failed beasue the file does not ahve a .ps1 extension. Specify a valid WIndows Powershell script name and then try again".
Even running the ps1 in Tosca directory i'm getting the same error message:
"No installation of Tosca could be found. Make sure it is correctly installed before running this script.
PS C:\Program Files (x86)\TRICENTIS\Tosca Testsuite>"

The only way I could see the add-on option is copy-paste the .dll files directly in Tosca.... Is this enohg? 

Appreciate your support

**Comment by alexisnouvel** [comment]
Hi ErVigue,
Launching the bat file from the _C:\Program Files (x86)\TRICENTIS\Tosca Testsuite_ directory can cause issue (because of the space in the path and administrator rights). Can you try to launch it from the Downloads directory?
