### ISSUE TITLE
PS1 Script Signing Certificate Has Expired

### ISSUE THREAD

**Issue by kdemancsik** [Neotys-Labs/Tricentis-Tosca#13]
The signing cert for `Install-NeoLoadToscaAddon.ps1` has expired on 14 March 2024. This script cannot be executed on machines that observe proper execution policies for powershell scripts. Please renew cert and re-sign this script. 

![image](https://github.com/Neotys-Labs/Tricentis-Tosca/assets/3525670/34440cb1-5a79-4547-8b9d-d9722930ac15)

**Comment by alexisnouvel** [comment]
The signature has been updated and the zip has been replaced.
