### ISSUE TITLE
Installed the add on but still unable to view the option of Neoload add on in Tosca

### ISSUE THREAD

**Issue by sudheesh1989** [Neotys-Labs/Tricentis-Tosca#9]
Installed the latest version of the Tosca Neoload integration (Neoload_Add-on_Tosca_v2.5.0.zip) but still unable to see the option of Neoload add on in the test case in Tosca. Tosca version is 14.0 P2.
![tosca snap](https://user-images.githubusercontent.com/31691793/134967658-75f8c94c-0efe-4215-ab98-db57e3f5ac84.JPG)

**Comment by guillaumebert** [comment]
Not reproductible with the latest versions of the addOn and Tosca
